import { SlidersHorizontal, X } from 'lucide-react'

const FilterBody = ({ filters, setFilters }) => <div className="space-y-7">
  <div><h3 className="mb-3 font-semibold text-navy">Price</h3><input type="range" min="25" max="250" value={filters.maxPrice} onChange={(e)=>setFilters({...filters,maxPrice:+e.target.value})} className="w-full accent-navy"/><div className="mt-2 flex justify-between text-xs text-charcoal/50"><span>$25</span><span>Up to ${filters.maxPrice}</span></div></div>
  {['category','brand','material'].map((group)=><div key={group}><h3 className="mb-3 capitalize font-semibold text-navy">{group}</h3><div className="space-y-2">{({category:['cookware','bakeware','utensils','appliances','storage','tableware'],brand:['Maison','Atelier','Foundry'],material:['Cast iron','Stoneware','Stainless steel','Wood']}[group]).map((value)=><label key={value} className="flex items-center gap-2 text-sm text-charcoal/70"><input type="checkbox" className="accent-navy" checked={filters[group]?.includes(value)} onChange={()=>setFilters({...filters,[group]:filters[group]?.includes(value)?filters[group].filter(v=>v!==value):[...(filters[group]||[]),value]})}/><span className="capitalize">{value}</span></label>)}</div></div>)}
  <div><h3 className="mb-3 font-semibold text-navy">Color</h3><div className="flex gap-2">{['#1B2B45','#FAF5EC','#704214','#B8B8B8'].map((color)=><button key={color} aria-label={`Filter color ${color}`} onClick={()=>setFilters({...filters,color})} style={{backgroundColor:color}} className={`h-7 w-7 rounded-full border ${filters.color===color?'ring-2 ring-navy ring-offset-2':''}`}/>)}</div></div>
  <label className="flex items-center gap-2 text-sm text-charcoal/70"><input type="checkbox" className="accent-navy" checked={filters.inStock} onChange={(e)=>setFilters({...filters,inStock:e.target.checked})}/> In stock only</label>
</div>

export default function FiltersSidebar({ filters, setFilters, open, setOpen }) {
  return <><aside className="hidden w-56 shrink-0 lg:block"><FilterBody filters={filters} setFilters={setFilters}/></aside><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg border border-navy/15 px-4 py-2 text-sm text-navy lg:hidden"><SlidersHorizontal size={16}/>Filters</button><div className={`fixed inset-0 z-[90] bg-navy/40 transition lg:hidden ${open?'opacity-100':'pointer-events-none opacity-0'}`}><div className={`absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto rounded-t-2xl bg-cream p-6 transition duration-500 ${open?'translate-y-0':'translate-y-full'}`}><div className="mb-6 flex items-center justify-between"><h2 className="font-serif text-2xl text-navy">Filters</h2><button onClick={()=>setOpen(false)}><X/></button></div><FilterBody filters={filters} setFilters={setFilters}/><button onClick={()=>setOpen(false)} className="mt-8 w-full rounded-lg bg-terracotta py-3 text-white">Show results</button></div></div></>
}
