import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { formatMoney } from '../data/catalog';

export default function CartPage() {
  const { cart, updateQuantity, removeFromCart } = useApp();
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  if (!cart.length) return <main className="mx-auto flex min-h-[65vh] max-w-xl flex-col items-center justify-center px-6 text-center"><ShoppingBag size={52} className="text-navy"/><h1 className="mt-6 font-serif text-4xl text-navy">Your cart is empty</h1><p className="mt-3 text-charcoal/65">Beautiful tools are waiting to make themselves useful.</p><Link to="/shop" className="mt-7 rounded-full bg-terracotta px-7 py-3 text-white">Continue shopping</Link></main>;
  return <main className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><h1 className="font-serif text-5xl text-navy">Your cart</h1><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_380px]">
    <section className="space-y-4">{cart.map(item => <article key={item.id} className="grid grid-cols-[100px_1fr] gap-5 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-[120px_1fr_auto]"><img src={item.image} alt={item.name} className="aspect-square rounded-lg object-cover"/><div><Link to={`/product/${item.id}`} className="font-serif text-xl text-navy">{item.name}</Link><p className="mt-1 text-sm text-charcoal/55">{item.material}</p><div className="mt-4 inline-flex items-center rounded-full border border-navy/15"><button onClick={()=>updateQuantity(item.id, Math.max(1,item.quantity-1))} className="p-2"><Minus size={15}/></button><span className="w-8 text-center text-sm">{item.quantity}</span><button onClick={()=>updateQuantity(item.id,item.quantity+1)} className="p-2"><Plus size={15}/></button></div></div><div className="col-start-2 flex items-center justify-between sm:col-start-3 sm:block sm:text-right"><strong>{formatMoney(item.price * item.quantity)}</strong><button onClick={()=>removeFromCart(item.id)} className="ml-5 text-navy/50 sm:mt-8 sm:block" aria-label={`Remove ${item.name}`}><Trash2 size={18}/></button></div></article>)}</section>
    <aside className="h-fit rounded-2xl bg-sand p-7 lg:sticky lg:top-28"><h2 className="font-serif text-2xl text-navy">Order summary</h2><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatMoney(subtotal)}</span></div><div className="flex justify-between"><span>Shipping</span><span>{subtotal >= 75 ? 'Free' : 'Calculated at checkout'}</span></div></div><div className="mt-6 flex justify-between border-t border-navy/15 pt-5 text-lg font-semibold"><span>Total</span><span>{formatMoney(subtotal)}</span></div><Link to="/checkout" className="mt-7 block rounded-full bg-terracotta px-6 py-3 text-center font-medium text-white">Proceed to checkout</Link><p className="mt-4 text-center text-xs text-charcoal/55">Secure checkout · 30-day returns</p></aside>
  </div></main>;
}
