import { useState } from 'react';
import { LockKeyhole, ShieldCheck } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { formatMoney } from '../data/catalog';

const fields = ['email','firstName','lastName','address','city','country','phone'];
export default function CheckoutPage(){
 const { cart }=useApp(); const [form,setForm]=useState({}); const [errors,setErrors]=useState({}); const total=cart.reduce((s,i)=>s+i.price*i.quantity,0);
 const submit=e=>{e.preventDefault(); const next=Object.fromEntries(fields.filter(k=>!form[k]?.trim()).map(k=>[k,'This field is required'])); setErrors(next);};
 const input=(name,label,type='text')=><label className="block text-sm text-navy">{label}<input type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})} className={`mt-2 w-full rounded-lg border bg-white px-4 py-3 outline-none focus:border-navy ${errors[name]?'border-terracotta':'border-navy/15'}`}/>{errors[name]&&<span className="mt-1 block text-xs text-terracotta">{errors[name]}</span>}</label>;
 return <main className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><h1 className="font-serif text-5xl text-navy">Checkout</h1><form onSubmit={submit} className={`mt-10 grid gap-10 lg:grid-cols-[1fr_390px] ${Object.keys(errors).length?'animate-[shake_.3s_ease]':''}`}><div className="space-y-8">
  <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl text-navy">Contact information</h2><div className="mt-5">{input('email','Email address','email')}</div></section>
  <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl text-navy">Shipping address</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{input('firstName','First name')}{input('lastName','Last name')}<div className="sm:col-span-2">{input('address','Street address')}</div>{input('city','City')}{input('country','Country')}{input('phone','Phone number','tel')}</div></section>
  <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl text-navy">Shipping method</h2><label className="mt-5 flex cursor-pointer justify-between rounded-xl border border-navy p-4"><span><input type="radio" defaultChecked className="mr-3"/>Standard delivery <small className="block pl-6 text-charcoal/55">3–5 business days</small></span><strong>{total>=75?'Free':'$8.00'}</strong></label></section>
  <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-3 text-navy"><ShieldCheck/><span className="text-sm">Encrypted, secure payment</span></div><h2 className="mt-5 font-serif text-2xl text-navy">Payment</h2><div className="mt-5 space-y-3"><label className="flex rounded-xl border border-navy p-4"><input type="radio" name="payment" defaultChecked className="mr-3"/>Mobile Money</label><label className="flex rounded-xl border border-navy/15 p-4"><input type="radio" name="payment" className="mr-3"/>Cash on delivery</label></div></section>
 </div><aside className="h-fit rounded-2xl bg-sand p-7 lg:sticky lg:top-28"><h2 className="font-serif text-2xl text-navy">Your order</h2><div className="mt-6 space-y-4">{cart.map(i=><div className="flex gap-3" key={i.id}><img src={i.image} alt={i.name} className="h-16 w-16 rounded-lg object-cover"/><div className="flex-1 text-sm"><p className="font-medium text-navy">{i.name}</p><p className="text-charcoal/50">Qty {i.quantity}</p></div><span className="text-sm">{formatMoney(i.price*i.quantity)}</span></div>)}</div><div className="mt-6 flex justify-between border-t border-navy/15 pt-5 text-lg font-semibold"><span>Total</span><span>{formatMoney(total)}</span></div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-terracotta px-6 py-3 font-medium text-white"><LockKeyhole size={18}/>Place order</button></aside></form></main>
}
